name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MDBOOK_VERSION: 0.5.2
      MDBOOK_TABS_VERSION: 0.3.4
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install mdBook toolchain
        run: |
          curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf -y | sh
          rustup update
          cargo install --version ${MDBOOK_VERSION} mdbook
          cargo install --version ${MDBOOK_TABS_VERSION} mdbook-tabs

      - name: Build with mdBook
        run: mdbook build
